# Generated by Django 4.2.4 on 2023-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_url", models.TextField(blank=True)),
                ("name", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=10)),
                ("age", models.IntegerField(default=0)),
                ("team", models.CharField(max_length=50)),
                ("league", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                ("date_game", models.DateTimeField(default=None)),
                ("opponent", models.CharField(max_length=50)),
                ("games_played", models.IntegerField(default=0)),
                ("games_started", models.IntegerField(default=0)),
                (
                    "minutes_played",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "field_goals_made",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "field_goals_attempted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "field_goal_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "three_pointers_made",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "three_pointers_attempted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "three_point_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "two_pointers_made",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "two_pointers_attempted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "two_point_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "effective_field_goal_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "free_throws_made",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "free_throws_attempted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "free_throw_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "offensive_rebounds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "defensive_rebounds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_rebounds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "assists",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "steals",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "blocks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "turnovers",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "personal_fouls",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
    ]
